# Generated by Django 5.2 on 2025-04-10 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biztrack_app', '0003_category_created_at_category_updated_at_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_url',
            field=models.TextField(default='Img'),
            preserve_default=False,
        ),
    ]
