# Generated by Django 5.2 on 2025-04-13 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biztrack_app', '0005_invoice_invoiceitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='qty',
            new_name='quantity',
        ),
    ]
