# Generated by Django 5.2 on 2025-04-18 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biztrack_app', '0007_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img_url',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='biztrack/images'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='biztrack_app.product'),
        ),
    ]
