# Generated by Django 5.2 on 2025-04-19 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biztrack_app', '0008_remove_product_img_url_alter_productimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='biztrack_app.invoice'),
        ),
    ]
